# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('owner_username', models.CharField(max_length=39)),
                ('owner_type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=140, unique=True)),
                ('description', models.TextField(max_length=191)),
                ('language', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('homepage', models.URLField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField()),
                ('stargazers_count', models.IntegerField()),
                ('forks_count', models.IntegerField()),
                ('subscribers_count', models.IntegerField()),
                ('fork', models.BooleanField()),
                ('has_issues', models.BooleanField()),
                ('has_projects', models.BooleanField()),
                ('has_downloads', models.BooleanField()),
                ('has_wiki', models.BooleanField()),
                ('has_pages', models.BooleanField()),
                ('open_issues_count', models.IntegerField()),
                ('topics', django_mysql.models.ListTextField(models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RepoStarring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField()),
                ('from_username', models.CharField(max_length=39)),
                ('repo_id', models.IntegerField()),
                ('repo_full_name', models.CharField(max_length=140)),
                ('starred_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=39, unique=True)),
                ('account_type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.URLField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bio', models.CharField(blank=True, max_length=160, null=True)),
                ('public_repos', models.IntegerField()),
                ('public_gists', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.IntegerField()),
                ('from_username', models.CharField(max_length=39)),
                ('to_user_id', models.IntegerField()),
                ('to_username', models.CharField(max_length=39)),
                ('relation', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together=set([('from_user_id', 'relation', 'to_user_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='repostarring',
            unique_together=set([('from_user_id', 'repo_id')]),
        ),
    ]
